# routedns-ingress — rsyslog rules for HAProxy and Keepalived
# Installed to /etc/rsyslog.d/49-routedns-ingress.conf

local0.*    /var/log/haproxy.log
& stop

local1.*    /var/log/keepalived.log
& stop
